function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "TrafficLight"};
	this.sidHashMap["TrafficLight"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "TrafficLight:1"};
	this.sidHashMap["TrafficLight:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "TrafficLight:1"};
	this.sidHashMap["TrafficLight:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "TrafficLight:5"};
	this.sidHashMap["TrafficLight:5"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Lamp1"] = {sid: "TrafficLight:6"};
	this.sidHashMap["TrafficLight:6"] = {rtwname: "<Root>/Lamp1"};
	this.rtwnameHashMap["<Root>/Lamp2"] = {sid: "TrafficLight:7"};
	this.sidHashMap["TrafficLight:7"] = {rtwname: "<Root>/Lamp2"};
	this.rtwnameHashMap["<Root>/red"] = {sid: "TrafficLight:2"};
	this.sidHashMap["TrafficLight:2"] = {rtwname: "<Root>/red"};
	this.rtwnameHashMap["<Root>/yellow"] = {sid: "TrafficLight:11"};
	this.sidHashMap["TrafficLight:11"] = {rtwname: "<Root>/yellow"};
	this.rtwnameHashMap["<Root>/green"] = {sid: "TrafficLight:12"};
	this.sidHashMap["TrafficLight:12"] = {rtwname: "<Root>/green"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "TrafficLight:1:4"};
	this.sidHashMap["TrafficLight:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "TrafficLight:1:1"};
	this.sidHashMap["TrafficLight:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "TrafficLight:1:3"};
	this.sidHashMap["TrafficLight:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "TrafficLight:1:2"};
	this.sidHashMap["TrafficLight:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "TrafficLight:1:5"};
	this.sidHashMap["TrafficLight:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:8"] = {sid: "TrafficLight:1:8"};
	this.sidHashMap["TrafficLight:1:8"] = {rtwname: "<S1>:8"};
	this.rtwnameHashMap["<S1>:9"] = {sid: "TrafficLight:1:9"};
	this.sidHashMap["TrafficLight:1:9"] = {rtwname: "<S1>:9"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
